### ISSUE TITLE
Missing parameters unhandled

### ISSUE THREAD

**Issue by leecalcote** [layer5io/kubeopenapi-jsonschema#9]
#### Description
When no parameters are provided, this executable panics.

#### Screenshots/Logs
```
➜  ~ /Users/lee/.meshery/bin/kubeopenapi-jsonschema-darwin
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at readFileSync (/Users/lee/.meshery/bin/kubeopenapi-jsonschema-darwin:239:55)
    at readSchema (/Users/lee/.meshery/bin/helper/toJSONSchema.js:33:16)
    at ToJSONSchema (/Users/lee/.meshery/bin/helper/toJSONSchema.js:82:19)
    at Object.<anonymous> (/Users/lee/.meshery/bin/index.js:25:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}
```

#### Environment:
- Host OS: Darwin

**Comment by leecalcote** [comment]
@utkarsh-pro this issue has gone stale. Is it worth the time to address?

**Comment by tangledbytes** [comment]
@leecalcote P #10 should fix this issue.
